/*!CK:162232635!*//*1449614393,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["HSuL4"]); }

__d("ImageExtensions",[],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports={GIF:"gif",JPG:"jpg",PNG:"png",ICO:"ico",BMP:"bmp",WEBP:"webp",BEST:"best",PNG2JPG:"png2jpg"};},null);
__d("PUWMethods",[],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports={DRAGDROP:"dragdrop",FILE_SELECTOR:"file_selector",VAULT:"vault",RECENT_PHOTOS:"recent_photos",PHOTOS_OF_YOU:"photos_of_you",METHOD_EDITOR:"editor",SUGGESTIONS:"suggestions",CAMERA:"camera",COPYPASTE:"copypaste"};},null);
__d("VideoCreatorProductType",[],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports={LEGACY:0,UNSPECIFIED:1,CORE_VIDEOS:2,LOOPS:3,ANIMATED_GIFS:4,SLIDESHOW:5,PROFILE_VIDEO:6,SPHERICAL:7,LIVE_PHOTO:8,BIRTHDAY_VIDEO:9,STORYLINE:10,FRIENDS_DAY_2016:11};},null);
__d('FBOverlayBase.react',['React'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();var i=h.createClass({displayName:'FBOverlayBase',render:function(){return h.Children.only(this.props.children);}});f.exports=i;},null);
__d('FBOverlayElement.react',['React','cloneWithProps','cx','joinClasses'],function a(b,c,d,e,f,g,h,i,j,k){if(c.__markCompiled)c.__markCompiled();var l=h.PropTypes,m={horizontal:{left:"_32rg",right:"_32rh",fit:k("_32rg","_32rh")},vertical:{top:"_32ri",bottom:"_32rj",fit:k("_32ri","_32rj")}},n=h.createClass({displayName:'FBOverlayElement',propTypes:{horizontal:l.oneOf(['left','right','fit']),vertical:l.oneOf(['top','bottom','fit'])},getDefaultProps:function(){return {horizontal:'fit',vertical:'fit'};},render:function(){var o=k("_32rk",m.horizontal[this.props.horizontal],m.vertical[this.props.vertical]);return i(h.Children.only(this.props.children),{className:o});}});f.exports=n;},null);
__d('FBOverlayContainer.react',['FBOverlayBase.react','FBOverlayElement.react','React','cx','invariant','joinClasses'],function a(b,c,d,e,f,g,h,i,j,k,l,m){if(c.__markCompiled)c.__markCompiled();var n=j.createClass({displayName:'FBOverlayContainer',propTypes:{children:function(o,p){var q=o[p],r=0;j.Children.forEach(q,function(s){if(s===null||s===undefined)return;switch(s.type){case h:r++;break;case i:break;default:l(0);}});!(r===1)?l(0):undefined;}},render:function(){return (j.createElement('div',babelHelpers._extends({},this.props,{className:m(this.props.className,"_23n-")}),this.props.children));}});f.exports=n;},null);
__d('XUIAmbientNUXBody.react',['React','XUICloseButton.react','cx','joinClasses'],function a(b,c,d,e,f,g,h,i,j,k){if(c.__markCompiled)c.__markCompiled();var l=h.PropTypes,m=h.createClass({displayName:'XUIAmbientNUXBody',propTypes:{onCloseButtonClick:l.func},render:function(){var n=k("_21es",this.props.className);return (h.createElement('div',{className:n},h.createElement(i,{shade:'light',className:"_36gl",onClick:this.props.onCloseButtonClick}),h.createElement('div',{className:"_36gn"},this.props.children)));}});f.exports=m;},null);
__d('XUIAmbientNUX.react',['HasLayerContextMixin','React','ReactLayer','ReactAbstractContextualDialog','XUIAmbientNUXTheme','XUIAmbientNUXBody.react'],function a(b,c,d,e,f,g,h,i,j,k,l,m){if(c.__markCompiled)c.__markCompiled();var n=i.PropTypes,o=300,p=380,q=j.createClass(k.createSpec({displayName:'XUIAmbientNUX',theme:l})),r=i.createClass({displayName:'XUIAmbientNUX',mixins:[h],propTypes:{alignment:n.oneOf(['left','center','right']),behaviors:n.object,context:n.object,contextRef:n.func,customwidth:n.number,hasActionableContext:n.bool,offsetX:n.number,offsetY:n.number,onCloseButtonClick:n.func,position:n.oneOf(['above','below','left','right']),shown:n.bool,width:n.oneOf(['wide','normal','auto','custom'])},_getWidth:function(){switch(this.props.width){case 'wide':return p;case 'custom':return this.props.customwidth;case 'auto':return null;default:return o;}},render:function(){return (i.createElement(q,{alignment:this.props.alignment,autoFocus:false,behaviors:this.props.behaviors,context:this.getContextNode(),focusContextOnHide:false,hasActionableContext:this.props.hasActionableContext,offsetX:this.props.offsetX,offsetY:this.props.offsetY,position:this.props.position,shown:this.props.shown,width:this._getWidth(this.props)},i.createElement(m,{onCloseButtonClick:this.props.onCloseButtonClick},this.props.children)));}});f.exports=r;},null);
__d('PagesEventObserver',['Banzai'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();var i='pages_client_logging',j={VITAL_WAIT:h.VITAL_WAIT,logData_DEPRECATED:function(k,l){var m={delay:l||h.VITAL_WAIT};h.post(i,k,m);},notify:function(event,k,l,m,n){var o=babelHelpers._extends({},l,{event_name:event,page_id:k,dedupe:m!==false}),p={delay:n||h.VITAL_WAIT};h.post(i,o,p);}};f.exports=j;},null);
__d('glyph',['ix'],function a(b,c,d,e,f,g){if(c.__markCompiled)c.__markCompiled();f.exports=c('ix');},null);
__d('PagesComposerActionsTypes',['keyMirror'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();var i=h({BACKDATE:null,SET_DRAFT:null,SCHEDULE:null,SET_ADS_POST:null,SET_BOOSTED_POST:null});f.exports=i;},null);
__d('PagesBanzaiEventListener',['Event','PagesEventObserver','Run'],function a(b,c,d,e,f,g,h,i,j){if(c.__markCompiled)c.__markCompiled();var k={registerLogEvent:function(l,m,n){var o=h.listen(l,'click',function(event){i.logData_DEPRECATED(m,n);});j.onLeave(function(){o.remove();});}};f.exports=k;},null);
__d('PagesTimelineController',['Arbiter'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();var i={LOAD_SECTION:'PagesTimelineController/loadSection',SECTION_FULLY_LOADED:'PagesTimelineController/sectionFullyLoaded',ACTIVATE_SCRUBBER_ITEM:'PagesTimelineController/activateScrubberItem',FIRST_POSTS_LOADED:'PagesTimelineController/firstPostsLoaded',REMOVE_SECTION:'PagesTimelineController/removeSection',RECENT_SECTION_KEY:'recent',NAV_BAR_LOADED:'PagesTimelineController/navBarLoaded',ADJUST_ADS:'PagesTimelineController/adjustAds',BOTTOM_OFFSET:100,loadSection:function(j){h.inform(this.LOAD_SECTION,{section_key:j},h.BEHAVIOR_STATE);},sectionFullyLoaded:function(j){h.inform(this.SECTION_FULLY_LOADED,{section_index:j},h.BEHAVIOR_PERSISTENT);},activateScrubberItem:function(j){h.inform(this.ACTIVATE_SCRUBBER_ITEM,{section_key:j},h.BEHAVIOR_STATE);},firstPostsLoaded:function(j){h.inform(this.FIRST_POSTS_LOADED,{section_key:j},h.BEHAVIOR_STATE);},removeSection:function(j){h.inform(this.REMOVE_SECTION,{section_key:j},h.BEHAVIOR_STATE);},navBarLoaded:function(){h.inform(this.NAV_BAR_LOADED,{},h.BEHAVIOR_STATE);},adjustAds:function(){h.inform(this.ADJUST_ADS,{},h.BEHAVIOR_STATE);}};f.exports=i;},null);
__d('VideoUploadFile',['fileSlice','ImageExtensions','VideoCreatorProductType','VideoUploadFeatureDetector'],function a(b,c,d,e,f,g,h,i,j,k){if(c.__markCompiled)c.__markCompiled();function l(m,n,o,p){'use strict';this.$VideoUploadFile1=m;this.$VideoUploadFile2=n;this.$VideoUploadFile3=o;this.$VideoUploadFile4=p;}l.fromFile=function(m){'use strict';var n=l.getExtensionFromFileName(m.name);return new this(null,m,m.size,n);};l.fromFileInput=function(m){'use strict';var n=null,o=null,p=l.getExtensionFromFileInput(m);if(k.supportsFileAPI()&&m.files.length){n=m.files[0];o=n.size;}return new this(m,n,o,p);};l.prototype.getFileInput=function(){'use strict';return this.$VideoUploadFile1;};l.prototype.getFile=function(){'use strict';return this.$VideoUploadFile2;};l.prototype.getSize=function(){'use strict';return this.$VideoUploadFile3;};l.prototype.getExtension=function(){'use strict';return this.$VideoUploadFile4;};l.prototype.getCreatorProduct=function(){'use strict';if(this.$VideoUploadFile4===i.GIF)return j.ANIMATED_GIFS;return j.CORE_VIDEOS;};l.prototype.getChunk=function(m,n){'use strict';return this.$VideoUploadFile2?h.call(this.$VideoUploadFile2,m,n):null;};l.getExtensionFromFileInput=function(m){'use strict';return this.getExtensionFromFileName(m.value);};l.getExtensionFromFileName=function(m){'use strict';return m.indexOf('.')!=-1?m.split('.').pop().toLowerCase():'';};f.exports=l;},null);